### ISSUE TITLE
Crash on unexpected battery percentage

### ISSUE THREAD

**Issue by ScoreUnder** [edge217/BatteryStatusInfo#37]
Right now I can't launch Minecraft with this mod active because I get the following error:

```

java.lang.IllegalArgumentException: Battery percentage must be between 0 and 1
	at com.edgeburnmedia.batterystatusinfo.BatteryStatus.<init>(BatteryStatus.java:19)
	at com.edgeburnmedia.batterystatusinfo.BatteryCheckerThread.getBatteryStatus(BatteryCheckerThread.java:39)
	at com.edgeburnmedia.batterystatusinfo.client.BatteryStatusInfoModClient.lambda$onInitializeClient$6(BatteryStatusInfoModClient.java:95)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$zkg000$fabric-lifecycle-events-v1$onStartTick(class_310.java:6178)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

My battery percentage is displaying as 95.78% in i3status, which is another story (#15), but this laptop regularly charges to just above 100% of the estimated capacity of the battery, such that it reports as about 104% full on i3status, so it would not be unusual for the battery to be more than 100% charged in day-to-day usage and this should not crash Minecraft.

**Comment by Edgeburn** [comment]
Fixed in #39
